Show differences in status
FluffyLabs/pvm-debugger pull request #182
Opened 2024-11-05 17:24 UTC by wkwiatek

2024-11-05 22:56 UTC, krystian50 requested changes

2024-11-05 22:56 UTC, krystian50 commented on src/components/Registers/index.tsx
> +                    <span style={{ color: getStatusColor(Number(value) as Status) }} test-id="program-status">
Maybe try to set Status as value type to prevent casting

2024-11-05 22:56 UTC, krystian50 commented on src/store/workers/workersSlice.ts
> +          if (event.data.command === Commands.STEP) {
You can try to refactor and use async post message I added.

2024-11-07 20:44 UTC, tomusdrw commented
<img width="428" alt="image" src="https://github.com/user-attachments/assets/b4096d02-8d8b-4eb3-8798-9bc26ae12eeb">

pvm shell showing an empty status, can you check if the value coming from the shell is incorrect? I think it should be within range so should display *something*.

2024-11-08 13:51 UTC, tomusdrw approved these changes
works good! Didn't look at the code.

2024-11-08 15:21 UTC, krystian50 approved these changes

2024-11-08 15:22 UTC, merged